[theme]
primaryColor = "#6eb52f"         # Net Zero green
backgroundColor = "#ffffff"      # White background
secondaryBackgroundColor = "#f0f0f5"  # Light gray for sidebar
textColor = "#262730"            # Dark gray text
font = "sans serif" 